-- Updated Snowflake Succession Plan Table Definition
-- Includes all collaborative workflow and OIDC compliance features

CREATE OR REPLACE TABLE HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL (
    -- Primary Key & Timestamps
    SUCCESSION_RECORD_ID NUMBER(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    ROW_CREATED_ON TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    
    -- Incumbent Information
    INCUMBENT_EMPLOYEE_ID VARCHAR(16777216) NOT NULL,
    INCUMBENT_FIRST_NAME VARCHAR(16777216) NOT NULL,
    INCUMBENT_LAST_NAME VARCHAR(16777216) NOT NULL,
    INCUMBENT_EMAIL VARCHAR(16777216),
    INCUMBENT_POSITION_ID VARCHAR(16777216),
    INCUMBENT_POSITION_TITLE VARCHAR(16777216),
    INCUMBENT_MANAGEMENT_LEVEL VARCHAR(16777216),
    INCUMBENT_JOB_LEVEL VARCHAR(16777216),
    INCUMBENT_SEGMENT VARCHAR(16777216),
    INCUMBENT_L2_LEADER_ID VARCHAR(16777216),
    INCUMBENT_L3_LEADER_ID VARCHAR(16777216),
    INCUMBENT_SUCCESSION_PLAN_SEGMENT_GROUP VARCHAR(16777216),
    
    -- Succession Plan Details
    CRITICAL_ROLE_IND BOOLEAN NOT NULL,
    INCUMBENT_ROLE_RESPONSIBILITIES VARCHAR(16777216) NOT NULL,
    INCUMBENT_TOP_SKILLS VARCHAR(16777216), -- JSON array
    INCUMBENT_TOP_PLE VARCHAR(16777216) NOT NULL,
    INCUMBENT_CONTRACT_END_DATE DATE,
    INCUMBENT_SOURCING_STRATEGY VARCHAR(16777216), -- JSON array
    INCUMBENT_ROLE_TYPE VARCHAR(16777216),
    INCUMBENT_ROLE_SCENARIO_PLAN VARCHAR(16777216) NOT NULL,
    INCUMBENT_ADDITIONAL_POSITION_TITLE VARCHAR(16777216),
    
    -- Successor Information
    SUCCESSOR_EMPLOYEE_ID VARCHAR(16777216) NOT NULL,
    SUCCESSOR_FIRST_NAME VARCHAR(16777216) NOT NULL,
    SUCCESSOR_LAST_NAME VARCHAR(16777216) NOT NULL,
    SUCCESSOR_EMAIL VARCHAR(16777216),
    SUCCESSOR_POSITION_ID VARCHAR(16777216),
    SUCCESSOR_POSITION_TITLE VARCHAR(16777216),
    SUCCESSOR_MANAGEMENT_LEVEL VARCHAR(16777216),
    SUCCESSOR_JOB_LEVEL VARCHAR(16777216),
    SUCCESSOR_SEGMENT VARCHAR(16777216),
    
    -- Successor Assessment
    SUCCESSOR_READINESS VARCHAR(16777216) NOT NULL,
    SUCCESSOR_FUTURE_READINESS_TIMING VARCHAR(16777216),
    SUCCESSOR_CONTRACT_END_DATE DATE,
    SUCCESSOR_STRENGTHS VARCHAR(16777216) NOT NULL,
    SUCCESSOR_TOP_SKILLS VARCHAR(16777216), -- JSON array
    SUCCESSOR_TOP_PLE VARCHAR(16777216) NOT NULL,
    SUCCESSOR_DEVELOPMENT_FOCUS VARCHAR(16777216) NOT NULL,
    SUCCESSOR_TALENT_ACTIONS VARCHAR(16777216) NOT NULL,
    
    -- Workflow Management (OIDC Compliant)
    REMOVED BOOLEAN NOT NULL DEFAULT FALSE,
    SUCCESSION_PLAN_STATUS VARCHAR(16777216) NOT NULL DEFAULT 'not_complete',
    SUBMITTED_BY VARCHAR(16777216), -- Email (OIDC PK)
    SUBMITTED_ON TIMESTAMP_NTZ(9),
    APPROVED_BY VARCHAR(16777216), -- Email (OIDC PK)
    APPROVED_ON TIMESTAMP_NTZ(9),
    EDIT_REQUESTED_BY VARCHAR(16777216), -- Email (OIDC PK)
    EDIT_REQUESTED_ON TIMESTAMP_NTZ(9),
    EDIT_COMMENTS VARCHAR(16777216), -- Currently unused but kept for future
    
    -- User Tracking & Collaboration
    ROW_CREATED_BY VARCHAR(16777216) NOT NULL, -- Email (OIDC PK)
    ROW_CREATED_TIER VARCHAR(16777216) NOT NULL, -- User tier (1, 2, 3)
    ROW_CREATED_USER_SEGMENTS VARCHAR(16777216), -- JSON array of user segments
    
    PRIMARY KEY (SUCCESSION_RECORD_ID)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS IDX_SUCCESSION_INCUMBENT_ID 
ON HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL (INCUMBENT_EMPLOYEE_ID);

CREATE INDEX IF NOT EXISTS IDX_SUCCESSION_STATUS 
ON HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL (SUCCESSION_PLAN_STATUS);

CREATE INDEX IF NOT EXISTS IDX_SUCCESSION_SUBMITTED_BY 
ON HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL (SUBMITTED_BY);

CREATE INDEX IF NOT EXISTS IDX_SUCCESSION_CREATED_ON 
ON HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL (ROW_CREATED_ON);

-- Comments for documentation
COMMENT ON TABLE HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL IS 
'Succession planning data with collaborative workflow support and OIDC compliance';

COMMENT ON COLUMN HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL.SUBMITTED_BY IS 
'Email address of user who submitted (OIDC primary key)';

COMMENT ON COLUMN HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL.APPROVED_BY IS 
'Email address of Tier 1 user who approved (OIDC primary key)';

COMMENT ON COLUMN HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL.ROW_CREATED_BY IS 
'Email address of user who created record (OIDC primary key)';

COMMENT ON COLUMN HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL.SUCCESSION_PLAN_STATUS IS 
'Workflow status: not_complete, saved, submitted, approved, needs_edit';

COMMENT ON COLUMN HR_STREAMLIT.SUCCESSION_PLAN.TBL_SL_SUCCESSION_PLAN_DETAIL.REMOVED IS 
'Soft delete flag for data integrity';
