# Succession Planning Tool Configuration

# Skills list for dropdowns
skills:
  - "Thinks Strategically"
  - "Plans and Prioritizes"
  - "Ensures Accountability"
  - "Collaborates"
  - "Instills Trust"
  - "Drives Engagement"
  - "Values Differences"
  - "Business Insight"
  - "Courage"
  - "Change Adaptability"

# PLE (Performance Leadership Excellence) list
ple_options:
  - "-- Select an Option --"  # Placeholder for required field
  - "Inspire Individual and Business Success"
  - "Define Strategies, Priorities, and Expectations"
  - "Provide Continuous Coaching and Feedback"
  - "Develop Self and Others and Support Career Aspirations"
  - "Demonstrate Care and Compassion"
  - "Create an Environment Where Disney Values are Experienced"

# Form dropdown options
form_options:
  sourcing_strategy:
    - "-- Select an Option --"
    - "Build (Internal hire)"
    - "Redesign: OD Evaluation Needed"
    - "Redesign: OD Evaluation Completed"
    - "External"
  
  role_type:
    - "Not Applicable"
    - "Succession Plan"
    - "Talent Pool"
    - "Redesign"
    - "External"
    - "No Talent backfill required"
  
  scenario_plan:
    - "-- Select an Option --"
    - "Direct Backfill"
    - "Split Position/New Position"
  
  readiness_level:
    - "-- Select an Option --"
    - "Ready Now"
    - "Ready Future"
  
  future_readiness_timing:
    - "-- Select an Option --"
    - "+1 to < 2 years"
    - "+2 to < 3 years"
    - "+3 to < 5 years"

# Database configuration
database:
  employee_db: "succession_db.sqlite"
  succession_plans_db: "succession_plans.sqlite"
  
  # Table names
  tables:
    employee: "employee"
    succession_plans: "succession_plans"
  
  # Search limits
  limits:
    employee_search: 50

# Database queries (using table names from config)
queries:
  search_employees: |
    SELECT
        SEGMENT_HIER_LEVEL_2_NAME, PREFERRED_NAME_FIRST_NAME,
        PREFERRED_NAME_LAST_NAME, EMPLOYEE_ID, POSITION_REFERENCE_ID,
        POSITION_NBR_DESCRIPTION, MANAGEMENT_LEVEL, JOB_LEVEL,
        DAYS_IN_MGMT_LEVEL, MGMT_LEVEL_GROUP, EMAIL_PRIMARY_WORK
    FROM {employee_table}
    WHERE LOWER(PREFERRED_NAME_LAST_NAME) LIKE LOWER(?)
    LIMIT {search_limit};
  
  get_latest_incumbent_values: |
    SELECT CRITICAL_ROLE, RESPONSIBILITIES, INCUMBENT_TOP_SKILLS, INCUMBENT_TOP_PLE,
           INCUMBENT_CONTRACT_END_DATE, SOURCING_STRATEGY, ROLE_TYPE, SCENARIO_PLAN,
           NEW_POSITION_TITLE
    FROM {succession_plans_table} 
    WHERE INCUMBENT_EMPLOYEE_ID = ?
    ORDER BY CREATED_AT DESC 
    LIMIT 1
  
  get_latest_successor_values: |
    SELECT SUCCESSOR_READINESS, SUCCESSOR_FUTURE_READINESS_TIMING,
           SUCCESSOR_CONTRACT_END_DATE, SUCCESSOR_STRENGTHS, SUCCESSOR_TOP_SKILLS,
           SUCCESSOR_TOP_PLE, SUCCESSOR_DEVELOPMENT_FOCUS, SUCCESSOR_TALENT_ACTIONS
    FROM {succession_plans_table} 
    WHERE SUCCESSOR_EMPLOYEE_ID = ?
    ORDER BY CREATED_AT DESC 
    LIMIT 1
  
  save_succession_plan: |
    INSERT INTO {succession_plans_table} (
        INCUMBENT_EMPLOYEE_ID, INCUMBENT_FIRST_NAME, INCUMBENT_LAST_NAME,
        INCUMBENT_EMAIL, INCUMBENT_POSITION, INCUMBENT_MANAGEMENT_LEVEL,
        INCUMBENT_JOB_LEVEL, INCUMBENT_SEGMENT,
        CRITICAL_ROLE, RESPONSIBILITIES, INCUMBENT_TOP_SKILLS, INCUMBENT_TOP_PLE,
        INCUMBENT_CONTRACT_END_DATE, SOURCING_STRATEGY, ROLE_TYPE, SCENARIO_PLAN,
        NEW_POSITION_TITLE,
        SUCCESSOR_EMPLOYEE_ID, SUCCESSOR_FIRST_NAME, SUCCESSOR_LAST_NAME,
        SUCCESSOR_EMAIL, SUCCESSOR_POSITION, SUCCESSOR_MANAGEMENT_LEVEL,
        SUCCESSOR_JOB_LEVEL, SUCCESSOR_SEGMENT,
        SUCCESSOR_READINESS, SUCCESSOR_FUTURE_READINESS_TIMING,
        SUCCESSOR_CONTRACT_END_DATE, SUCCESSOR_STRENGTHS, SUCCESSOR_TOP_SKILLS,
        SUCCESSOR_TOP_PLE, SUCCESSOR_DEVELOPMENT_FOCUS, SUCCESSOR_TALENT_ACTIONS
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

# UI Configuration
ui:
  page_title: "Succession Planning Tool"
  layout: "wide"
  logo_path: "people_insights_logo.png"
  logo_width: 100

# Avatar/Photo configuration
avatar:
  base_url: "https://rostr.disney.com/api/v2/people/{employee_id}/avatars/thumbnail_large"
  token: "abc4fc58f30914f6d99faa8a31f4d44c"
  default_width: 50
  # Full URL template
  url_template: "https://rostr.disney.com/api/v2/people/{employee_id}/avatars/thumbnail_large?locale=en&token=abc4fc58f30914f6d99faa8a31f4d44c"

# PowerPoint configuration
powerpoint:
  template_file: "succession_profile_template.pptx"
  successors_per_slide: 3
  slide_width: 10.0  # inches
  slide_height: 7.5  # inches
  font_family: "Calibri"
  title_font_size: 18
  content_font_size: 12
  max_text_length: 80
  
  # Auto-repair settings
  auto_repair: true
  repair_method: "standard"  # Options: "standard", "temp_file", "deep_clean"

# Form validation rules
validation:
  min_search_length: 2
  max_search_results: 50
  max_skills_selection: 3
